# Generated by Django 4.2.7 on 2025-09-09 06:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = []
