# Generated by Django 4.2.7 on 2025-09-11 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_rbacrole_usersession_usersecurityprofile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("medical_license", models.CharField(blank=True, max_length=100)),
                ("specialization", models.CharField(blank=True, max_length=200)),
                ("years_of_experience", models.IntegerField(blank=True, null=True)),
                ("workplace", models.CharField(blank=True, max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("additional_notes", models.TextField(blank=True)),
                (
                    "registration_ip",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("verification_token", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "registration_notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="registratio_status_0f4583_idx"
                    ),
                    models.Index(fields=["email"], name="registratio_email_221995_idx"),
                    models.Index(
                        fields=["created_at"], name="registratio_created_47f78d_idx"
                    ),
                ],
            },
        ),
    ]
