[build]
builder = "NIXPACKS"

[deploy]
startCommand = "mkdir -p staticfiles && python manage.py collectstatic --noinput && python manage.py migrate && python setup_railway_admin.py && python approve_railway_admin.py && gunicorn medixscan_project.wsgi:application"
healthcheckPath = "/ping/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NIXPACKS_PYTHON_VERSION = "3.11"