# Railway nixpacks configuration for Python/Django
[providers]
python = "3.11"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn medixscan_project.wsgi:application --bind 0.0.0.0:$PORT --workers=2"

# Explicitly disable Docker detection
[build]
buildpack = false
dockerfile = false