# Procfile for Railway deployment
web: python manage.py migrate && python manage.py collectstatic --noinput && gunicorn medixscan_project.wsgi:application --bind 0.0.0.0:$PORT
release: python manage.py migrate
